# 应用启动后所监听的端口，可以不配置，默认就是8080端口
server:
  port: 10810

# Eureka相应的配置
eureka:
  client:
    register-with-eureka: false #用来控制当Spring Boot启动服务完成后是否将该服务注册到服务治理服务器上
    fetch-registry: false #应用启动后不需要从服务治理服务器中同步已注册的服务注册列表数据到本地
    serviceUrl:
      defaultZone: http://localhost:10810/eureka/,http://localhost:10811/eureka/
  server:
    wait-time-in-ms-when-sync-empty: 5