# 应用启动后所监听的端口，可以不配置，默认就是8080端口
server:
  port: 10850
spring:
  application:
    name: config-server #服务名称
  # config配置
  cloud:
    config:
      server:
        git:
          uri: https://github.com/imyanger/springcloud-project/
          search-paths: p6-config/config-server/config
          username: 
          password: 
      label: master

# Eureka相应的配置
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:10810/eureka/
  instance:
    prefer-ip-address: false #使用feign时需要指定为false，否则注册到ribbon服务列表上的服务显示机器名
    instance-id: ${spring.cloud.client.ip-address}-${server.port} #在eureka注册表上显示ip:port
